trigger:
  - master

pool:
  vmImage: 'macOS 10.13'

steps:
#Node Install
- task: NodeTool@0
  displayName: Node install
  inputs:
    versionSpec: '11.x'

- script: |
    pip install awscli
  displayName: 'Install AWS CLI'

- bash: |
    npm i -g npm@6.5
    /usr/local/bin/npm ci
    /usr/local/bin/npm run build-storybook
  displayName: 'Building Storybook' 

- script: cp -r storybook-static pangolins
